// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcwAzfQN_UO0sf6q1gYaNiUslSiKetvOk',
    appId: '1:435517410373:web:615db215b6f56378ec672c',
    messagingSenderId: '435517410373',
    projectId: 'flutter-food-delivery-40e7c',
    authDomain: 'flutter-food-delivery-40e7c.firebaseapp.com',
    storageBucket: 'flutter-food-delivery-40e7c.appspot.com',
    measurementId: 'G-2VCHS5FNX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBlazPThFpTmL-ZeVGnnzD-Owbg0Sncj4',
    appId: '1:435517410373:android:835beecded3050c0ec672c',
    messagingSenderId: '435517410373',
    projectId: 'flutter-food-delivery-40e7c',
    storageBucket: 'flutter-food-delivery-40e7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPZDhNuPTVuhxyjEPwJumMhnLuSb8XNE',
    appId: '1:435517410373:ios:1e12da29f66bc6dfec672c',
    messagingSenderId: '435517410373',
    projectId: 'flutter-food-delivery-40e7c',
    storageBucket: 'flutter-food-delivery-40e7c.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPZDhNuPTVuhxyjEPwJumMhnLuSb8XNE',
    appId: '1:435517410373:ios:1e12da29f66bc6dfec672c',
    messagingSenderId: '435517410373',
    projectId: 'flutter-food-delivery-40e7c',
    storageBucket: 'flutter-food-delivery-40e7c.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcwAzfQN_UO0sf6q1gYaNiUslSiKetvOk',
    appId: '1:435517410373:web:458fa0598a508fceec672c',
    messagingSenderId: '435517410373',
    projectId: 'flutter-food-delivery-40e7c',
    authDomain: 'flutter-food-delivery-40e7c.firebaseapp.com',
    storageBucket: 'flutter-food-delivery-40e7c.appspot.com',
    measurementId: 'G-0BWYLBTEM4',
  );
}
